export const MENU = {
  HOME: "Home",
  BESTSELLERS: "BestSellers",
  BLOGS: "Blogs",
  WISHLIST: "Wishlist",
  CART: "Cart",
  PROFILE: "Profile",
} as const;
export const COMMON = {
  LOGIN: "LOGIN",
  SIGNIN: "Sign in",
  SIGNUP: "Sign up",
  REMEBERME: "Remember me",
  FORGOTPASS: "Forgot Password?",
  GOOGLE: "Login With Google",
  FACEBOOK: "Login With Facebook",
  HAVEANACCOUNT: "Already have an account ",
  BESTSELLERS: "Best Sellers",
  FILTERS: "Filters",
  FILTER_BY_PRODUCT: "Filter by product",
  ALL_PRODUCTS: "All Products",
  SEE_ALL: "See all",
  SEE_MORE: "See more",
  BACK: "Back",
  SHIPPING: "Shipping",
  STANDARD_SHIPPING: "Standard Shipping",
  EXPRESS_SHIPPING: "Express Shipping",
  PRICE: "Price",
  HIGH: "Hight",
  CUSTOM_PRICE: "Custom",
  MAIN: "main",
  OCCASIONS: "occasions",
  PRODUCTS: "products",
  RECIPIENTS: "recipients",

  READ_MORE: "Read More",
  BEST_SELLERS: "Best Sellers",
} as const;
